services:
  cvc-api:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - robot-services-network

networks:
  robot-services-network:
    driver: bridge
