"""Порты (интерфейсы) для адаптеров. Без внешних зависимостей."""

from typing import Any, Dict, List, Optional, Protocol, Tuple, Union


class IClassifier(Protocol):
    """Порт классификатора команд (предсказание, эмбеддинги, обучение, сохранение/загрузка)."""

    def predict(
        self, text: str, return_confidence: bool = False
    ) -> Union[str, Tuple[str, float]]: ...
    def predict_batch(
        self, texts: List[str], return_confidence: bool = False
    ) -> Union[List[str], Tuple[List[str], List[float]]]: ...
    def get_embeddings(self, texts: List[str]) -> List[List[float]]: ...
    def train(
        self,
        texts: List[str],
        labels: List[str],
        num_iterations: int = 20,
        num_epochs: int = 1,
        batch_size: int = 16,
        learning_rate: float = 2e-5,
        device: Optional[str] = None,
    ) -> None: ...
    def save(self, model_path: str) -> None: ...
    def load(self, model_path: str, confidence_threshold: Optional[float] = None) -> None: ...


class IExampleRepository(Protocol):
    """Порт репозитория примеров (хранение и выборка для обучения)."""

    def init(self, db_path: str, csv_path: Optional[str] = None) -> None: ...
    def get_all(self, db_path: str) -> List[Tuple[int, str, str]]: ...
    def get_by_id(self, db_path: str, example_id: int) -> Optional[Tuple[int, str, str]]: ...
    def add(self, db_path: str, text: str, command: str) -> int: ...
    def delete(self, db_path: str, example_id: int) -> bool: ...
    def get_examples_for_training(
        self, db_path: str
    ) -> Tuple[List[str], List[str], List[int]]: ...
    def get_trained_examples_by_labels(
        self, db_path: str, labels: List[str], limit_per_label: int
    ) -> Tuple[List[str], List[str], List[int]]: ...
    def mark_as_trained(self, db_path: str, example_ids: List[int]) -> None: ...
    def count(self, db_path: str) -> int: ...
    def get_training_stats(self, db_path: str) -> Dict[str, Any]: ...
    def reset_training_status(self, db_path: str) -> int: ...
    def check_connection(self, db_path: str) -> bool: ...
